name: Tests + Coverage

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test

<<<<<<< HEAD
      # 🔥 ADD THIS STEP (IMPORTANT)
=======
>>>>>>> f216e8f14cb2d39b0e8325b11051b354c3683bcb
      - name: Check coverage file exists
        run: ls -R coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
<<<<<<< HEAD
          fail_ci_if_error: true
=======
          fail_ci_if_error: true
>>>>>>> f216e8f14cb2d39b0e8325b11051b354c3683bcb
